### ISSUE TITLE
Hash is treated as wildcard matcher?

### ISSUE THREAD

**Issue by yhara** [rr/rr#54]
Hi,

In the following test case, I expected test_foo to fail because `{a: 1}` is not equal to `{a: 1, b: 2}`. But when I save this as a.rb and run `ruby a.rb`, rr does not raise an error.
(tested with rr 1.1.2 and git master, ruby 2.0.0 p247)

```
require 'test/unit'
require 'rr'

class TestFoo < Test::Unit::TestCase
  def foo(hash)
  end

  def test_foo
    mock(self).foo(a: 1)
    foo(a: 1, b: 2)
  end
end
```

Is this a bug or intended?

**Comment by sshaw** [comment]
This also happens with arrays:

```ruby
class BsTest < Minitest::Test
  def test_bs
    o = Object.new
    def o.foo(n)
      p 123
    end

    mock(o).foo([1])
    o.foo([1,2])
  end
end
```

Note that the problem also exists when calling `mock(o).foo.with([1])`

**Comment by kou** [comment]
Thanks for your reports.
I've fixed both `Hash` and `Array`.

**Comment by brandonduff** [comment]
This is still broken when expecting empty arrays.

```
require 'spec_helper'

describe 'RR Array' do
  it 'breaks' do
    o = Object.new
    def o.foo(n)
      p 123
    end

    mock(o).foo([])
    o.foo([345])
  end
end
```

This rspec test should fail, but passes.
